# Generated by Django 4.1.2 on 2022-11-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0002_alter_movie_options_alter_movie_classification_and_more'),
        ('room', '0003_alter_room_options_alter_room_capacity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=125, unique=True, verbose_name='codigo de funcion')),
                ('date', models.DateField(verbose_name='fecha')),
                ('time', models.TimeField(verbose_name='hora')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='pelicula')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room', verbose_name='sala')),
            ],
            options={
                'verbose_name': 'funcion',
                'verbose_name_plural': 'funciones',
            },
        ),
    ]
