# Generated by Django 4.1.2 on 2022-10-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125, verbose_name='Nombre sala')),
                ('code', models.CharField(max_length=125, unique=True, verbose_name='Codigo sala')),
                ('capacity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
    ]
