# Generated by Django 4.1.2 on 2022-10-31 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='Capacidad'),
        ),
    ]
