# Generated by Django 4.1.2 on 2022-11-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_capacity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'sala', 'verbose_name_plural': 'salas'},
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='capacidad'),
        ),
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(max_length=125, unique=True, verbose_name='codigo de sala'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=125, verbose_name='nombre de sala'),
        ),
    ]
