# Generated by Django 4.1.2 on 2022-10-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125, verbose_name='Nombre pelicula')),
                ('code', models.CharField(max_length=125, unique=True, verbose_name='Codigo pelicula')),
                ('classification', models.CharField(choices=[('TP', 'TP'), ('7', '7'), ('12', '12'), ('15', '15'), ('18', '18')], default='Sin clasificacion', max_length=125, verbose_name='Clasificacion')),
            ],
            options={
                'verbose_name': 'Pelicula',
                'verbose_name_plural': 'Peliculas',
            },
        ),
    ]
