# Generated by Django 4.1.2 on 2022-11-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'pelicula', 'verbose_name_plural': 'peliculas'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='classification',
            field=models.CharField(choices=[('TP', 'TP'), ('7', '7'), ('12', '12'), ('15', '15'), ('18', '18')], default='sin clasificacion', max_length=125, verbose_name='clasificacion'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='code',
            field=models.CharField(max_length=125, unique=True, verbose_name='codigo de pelicula'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=125, verbose_name='nombre de pelicula'),
        ),
    ]
